package yoo

const (
	VERSION = 0x01
	CONSTANT_STRINGS_START = 0x00
  CONSTANT_STRINGS_END = 0x01
  CONSTANT_IDENTIFIER = 0x02
  CONSTANT_CALL = 0x03
	CONSTANT_STRING = 0x04
	CONSTANT_MEMBER = 0x05
	CONSTANT_VARIABLE = 0x06
	CONSTANT_NULL = 0x07
	PRIMITIVE_VALUE = "[[PRIMITIVE VALUE]]"
)
